### ISSUE TITLE
PyLint import errors

### ISSUE THREAD

**Issue by Adanteh** [frankbroniewski/visual-studio-code-qgis#1]
Figured I'd put a question out. although my intellisense seems to work using this, I'm still getting pylint errors in VS code along the lines of:
`E0611: No name 'QgsProject' in module 'qgis.core'`
Any tips to fix that? 

edit: Fix typo pylint message

**Comment by lucamanga** [comment]
**QgsProject**, not QqgsProject

**Comment by Adanteh** [comment]
Sorry that was a typo. I do have QgsProject.

![image](https://user-images.githubusercontent.com/1355127/45758093-1cee6f00-bc25-11e8-8fa6-d3476cf55821.png)
Goes for all imports

**Comment by frankbroniewski** [comment]
I believe, you need to configure your pylint configuration file and whitelist the qgis and qt5 modules. I have the following line in my .pylintrc
`extension-pkg-whitelist=PyQt5,qgis`

**Comment by Adanteh** [comment]
Thanks a ton, that did solve it.

**Comment by lucamanga** [comment]
> I believe, you need to configure your pylint configuration file and whitelist the qgis and qt5 modules. I have the following line in my .pylintrc
> `extension-pkg-whitelist=PyQt5,qgis`

This should be in Project README

**Comment by frankbroniewski** [comment]
Done :-)
